### ISSUE TITLE
Not working with latest runtime

### ISSUE THREAD

**Issue by johnuopini** [canontech/staking-payouts#89]
With latest DOT runtime script fails with the following message:
```
Error: createType(RuntimeDispatchInfo):: Struct: failed on weight: u64:: Assertion failed
    at createTypeUnsafe (.//staking-payouts/node_modules/@polkadot/types-create/create/type.cjs:73:18)
    at TypeRegistry.createTypeUnsafe (.//staking-payouts/node_modules/@polkadot/types/create/registry.cjs:419:46)
    at RpcCore._formatOutput (.//staking-payouts/node_modules/@polkadot/rpc-core/bundle.cjs:413:21)
    at RpcCore._formatResult (.//staking-payouts/node_modules/@polkadot/rpc-core/bundle.cjs:237:27)
    at callWithRegistry (.//staking-payouts/node_modules/@polkadot/rpc-core/bundle.cjs:262:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This happens only when the actual payout transaction is tried, not before

**Comment by emostov** [comment]
What version are using? I just released v1.4.4 that should fix this

**Comment by johnuopini** [comment]
I am on latest still facing the issue trying to claim on polkadot

**Comment by alko89** [comment]
I've tested it with the latest version and can confirm working for me. Thanks! :+1:

**Comment by johnuopini** [comment]
Fetching repo again and cleaning deps did the trick :)
